##############################################################################################
# Purpose: Save the filtered PSI value files --
##############################################################################################

rm(list=ls())
library(data.table)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(GenomicDataCommons)
library(biomaRt)
library(seqinr)
library(pheatmap)
library(ggrepel)
library(ggpp)
library(dplyr)
library(TCGAbiolinks)


packageVersion("data.table")
packageVersion("ggplot2")
packageVersion("ggrepel")
packageVersion("dplyr")
packageVersion("GenomicDataCommons")
packageVersion("biomaRt")
packageVersion("seqinr")
packageVersion("pheatmap")
packageVersion("ggrepel")
packageVersion("ggpp")
packageVersion("dplyr")
packageVersion("TCGAbiolinks")

install.packages("data.table")
install.packages("ggplot2")
install.packages("ggrepel")
install.packages("dplyr")
install.packages("GenomicDataCommons")
install.packages("biomaRt")
install.packages("seqinr")
install.packages("pheatmap")
install.packages("ggpp")
install.packages("TCGAbiolinks")
install.packages("Rcpp")
install.packages("stringr")